[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "arzolay_gonzalez_perez_aan3_streamlit_penguins_example"
version = "1.0.0"
dependencies = ["pandas", "numpy", "seaborn", "streamlit"]
